# Penyelesaian sistem persamaan linier tiga variabel dan empat variabel dengan menggunakan eliminasi gaussian

## Eliminasi Gauss

Eliminasi Gauss adalah metode untuk menyelesaikan sistem linear dengan mereduksi matriks augmented ke bentuk trapesium (upper triangular / row echelon) menggunakan operasi baris elementer, lalu melakukan back-substitution untuk mendapatkan nilai variabelnya.

Selesaikan dengan menggunakan eleminasi gauss

In [1]:
from IPython.display import display, Math

# Menampilkan sistem persamaan dalam format LaTeX
display(Math(r'''
\begin{cases}
2x + y - z = 8 \\
-3x - y + 2z = -11 \\
-2x + y + 2z = -3 \\
\end{cases}
'''))

<IPython.core.display.Math object>

In [4]:
import numpy as np

# Matriks koefisien
A = np.array([
    [2, 1, -1],
    [-3, -1, 2],
    [-2, 1, 2]
])

print(A)
# Matriks konstanta
B = np.array([8, -11, -3])

# Menyelesaikan sistem persamaan
solution = np.linalg.solve(A, B)

# Menampilkan hasil
print("Nilai x =", solution[0])
print("Nilai y =", solution[1])
print("Nilai z =", solution[2])

[[ 2  1 -1]
 [-3 -1  2]
 [-2  1  2]]
Nilai x = 2.0000000000000004
Nilai y = 2.9999999999999996
Nilai z = -0.9999999999999994
