# Penyelesaian sistem persamaan linier tiga variabel dan empat variabel dengan menggunakan eliminasi gaussian

## Eliminasi Gauss

Eliminasi Gauss adalah metode untuk menyelesaikan sistem linear dengan mereduksi matriks augmented ke bentuk trapesium (upper triangular / row echelon) menggunakan operasi baris elementer, lalu melakukan back-substitution untuk mendapatkan nilai variabelnya.

In [1]:
import numpy as np

A = np.array([
    [1, 1, 1],
    [2, 1, 1],
    [1, 2, 3]
], dtype=float)
print(A)

b = np.array([6, 14, 14], dtype=float)
print(b)

n = len(b)

# Forward Elimination
for i in range(n):
    for j in range(i+1, n):
        ratio = A[j][i] / A[i][i]
        A[j] = A[j] - ratio * A[i]
        b[j] = b[j] - ratio * b[i]

# Back Substitution
x = np.zeros(n)
x[n-1] = b[n-1] / A[n-1][n-1]

for i in range(n-2, -1, -1):
    x[i] = (b[i] - np.sum(A[i][i+1:] * x[i+1:])) / A[i][i]

print("Solusi:")
print(x)

[[1. 1. 1.]
 [2. 1. 1.]
 [1. 2. 3.]]
[ 6. 14. 14.]
Solusi:
[  8. -12.  10.]


In [2]:
import numpy as np

A = np.array([
    [1, 1, 1, 1],
    [2, -1, 1, 1],
    [1, 2, -1, 1],
    [1, 1, 2, -1]
], dtype=float)

b = np.array([10, 8, 7, 6], dtype=float)

x = np.linalg.solve(A, b)

print("Matrix A = ")
print(A)
print("Matrix b = ")
print(b)
print("Solusi:")
print(x)

Matrix A = 
[[ 1.  1.  1.  1.]
 [ 2. -1.  1.  1.]
 [ 1.  2. -1.  1.]
 [ 1.  1.  2. -1.]]
Matrix b = 
[10.  8.  7.  6.]
Solusi:
[2.13333333 2.06666667 2.53333333 3.26666667]
